### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by AriseKing** [Jack-Huys/Filetransfer_server#1]
求相关帮助文档（如何运行程序）

**Comment by Jack-Huys** [comment]
程序需要使用g++编译器编译

**Comment by Jack-Huys** [comment]
CC = g++
LD = g++

CFLAGS += -Wall -O2
CFLAGS += -l./inc
CFLAGS += -std=c++11

LDFLAGS += -std=c++11

OBJS += serverMain.cc clientMain.cc server.o client.o

all: $(OBJS)
	$(LD) $(LDFLAGS) serverMain.cc server.o -o chat_server
	$(LD) $(LDFLAGS) clientMain.cc client.o -o chat_client

server.o: server.cc server.h common.h
	$(CC) $(CFLAGS) -c server.cc

client.o: client.cc client.h common.h
	$(CC) $(CFLAGS) -c client.cc

.PHONY:clear
clear:
	rm -f *.o chat_server chat_client
	@echo "clear over!"

**Comment by Jack-Huys** [comment]
参考以上makefile修改 就能编译出可执行文件了
